# Generated by Django 3.2.5 on 2021-08-24 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tel', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('ville', models.CharField(max_length=50)),
                ('statut', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=40)),
                ('prix', models.IntegerField()),
                ('description', models.TextField()),
                ('lieu', models.CharField(max_length=40)),
                ('etat_stock', models.CharField(blank=True, choices=[('Bon', 'Bon'), ('Moyen', 'Moyen'), ('Epuisé', 'Epuisé')], max_length=15)),
                ('image_produit', models.ImageField(blank=True, null=True, upload_to='image_produit')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('Lieu_livraison', models.CharField(max_length=40)),
                ('date_commande', models.DateField(auto_now_add=True)),
                ('ETAT', models.CharField(choices=[('Livré', 'Livré'), ('En cours', 'En cours'), ('Annulé', 'Annulé')], default='En cours', max_length=15)),
                ('date_livraison', models.DateField(null=True)),
                ('statut', models.BooleanField(default=False)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.produit')),
            ],
        ),
    ]
