# Generated by Django 3.2.5 on 2021-09-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210908_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='slug',
        ),
    ]
