# Generated by Django 3.2.7 on 2022-04-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_commande_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
